In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [66]:
df = pd.read_csv('homeprices.csv')

In [67]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [68]:
df.dtypes

area          int64
bedrooms    float64
age           int64
price         int64
dtype: object

In [69]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [70]:
df.describe()

area  bedrooms       age          price
count     5.000000  4.000000   5.00000       5.000000
mean   3280.000000  3.750000  18.20000  616000.000000
std     540.370243  0.957427   8.01249   83919.604384
min    2600.000000  3.000000   8.00000  550000.000000
25%    3000.000000  3.000000  15.00000  565000.000000
50%    3200.000000  3.500000  18.00000  595000.000000
75%    3600.000000  4.250000  20.00000  610000.000000
max    4000.000000  5.000000  30.00000  760000.000000

In [71]:
df['bedrooms'].describe()
# df.bedrooms.describe()

count    4.000000
mean     3.750000
std      0.957427
min      3.000000
25%      3.000000
50%      3.500000
75%      4.250000
max      5.000000
Name: bedrooms, dtype: float64

In [72]:
# df.bedrooms.mean()
df['bedrooms'].mean()

3.75

In [73]:
import math
median_bedrooms = math.floor(df['bedrooms'].mean())
median_bedrooms

3

In [87]:
# df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df['bedrooms'].fillna(median_bedrooms, inplace = True)

In [88]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [76]:
from sklearn import linear_model

In [77]:
lr = linear_model.LinearRegression()

In [78]:
lr.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [80]:
lr.coef_
# m

array([   137.25, -26025.  ,  -6825.  ])

In [81]:
lr.intercept_

383724.9999999998

In [82]:
lr.predict([[3000, 3, 40]])

array([444400.])

In [83]:
137.25*3000+-26025*3-6825*40+383724.9999999998

444399.9999999998

In [84]:
lr.predict([[2500, 4, 5]])

array([588625.])